# Generated by Django 4.1 on 2023-11-24 01:17

from django.db import migrations, models
import receipt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fined', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipt', models.FileField(upload_to=receipt.models.get_upload_path)),
            ],
        ),
    ]
