# Generated by Django 4.1 on 2024-01-09 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import receipt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fined', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=receipt.models.get_upload_path)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_set', to='files.file_document')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fined', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=receipt.models.get_upload_path)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('person_document', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='files.person_document')),
            ],
        ),
    ]
