# Generated by Django 4.1 on 2023-11-24 02:40

from django.db import migrations, models
import django.db.models.deletion
import receipt.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0033_rename_expired_date_filelog_expiry_date'),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.file_document'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fined',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=receipt.models.get_upload_path),
        ),
    ]
