# Generated by Django 4.1 on 2024-01-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_receipt',
            old_name='timestamp',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='timestamp',
            new_name='invoice_date',
        ),
    ]
