# Generated by Django 4.1 on 2023-12-12 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_receipt_file_alter_receipt_fined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
