# Generated by Django 4.1 on 2024-01-08 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0035_person_document_company'),
        ('receipt', '0004_person_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_receipt',
            name='person_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='files.person_document'),
        ),
    ]
