# Generated by Django 4.1 on 2024-01-08 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0035_person_document_company'),
        ('receipt', '0005_alter_person_receipt_person_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_set', to='files.file_document'),
        ),
    ]
