# Generated by Django 4.1 on 2024-01-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_company_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'unique_together': {('department_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='File_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('agency', models.CharField(default='Default Agency Name', max_length=50)),
                ('upload_file', models.FileField(upload_to=files.models.get_upload_path)),
                ('renewal_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('department_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_fullname', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('upload_file', models.FileField(upload_to=files.models.get_upload_path)),
                ('renewal_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_file', models.FileField(blank=True, null=True, upload_to=files.models.get_upload_path)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_logs', to='files.person_document')),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_file', models.FileField(blank=True, null=True, upload_to=files.models.get_upload_path)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_logs', to='files.file_document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
