# Generated by Django 4.1 on 2023-10-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_filelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelog',
            old_name='file_document',
            new_name='file',
        ),
    ]
