# Generated by Django 4.1 on 2023-10-23 02:03

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_rename_file_document_filelog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_document',
            name='upload_file',
            field=models.FileField(upload_to=files.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
