# Generated by Django 4.1 on 2023-11-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_alter_file_document_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_document',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.department'),
        ),
    ]
