# Generated by Django 4.1 on 2023-11-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_file_document_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='previous_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_file_logs', to='files.file_document'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_logs', to='files.file_document'),
        ),
    ]
