# Generated by Django 4.1 on 2023-11-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_filelog_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
