# Generated by Django 4.1 on 2023-11-22 01:29

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_remove_filelog_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='previous_file',
            field=models.FileField(upload_to=files.models.get_upload_path),
        ),
    ]
