# Generated by Django 4.1 on 2023-11-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_filelog_previous_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file_document'),
        ),
    ]
