# Generated by Django 4.1 on 2023-11-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_filelog_expired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelog',
            name='expired_date',
        ),
        migrations.AlterField(
            model_name='filelog',
            name='previous_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_file_logs', to='files.file_document'),
        ),
    ]
