# Generated by Django 4.1 on 2023-11-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_remove_filelog_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='previous_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
