# Generated by Django 4.1 on 2023-11-22 05:30

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0027_alter_filelog_previous_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='previous_file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.get_upload_path),
        ),
    ]
