# Generated by Django 4.1 on 2023-11-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0028_alter_filelog_previous_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='expired_date',
            field=models.DateField(default=None),  # Add this line
            preserve_default=False,
        ),
    ]
