# Generated by Django 4.1 on 2023-11-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0030_alter_filelog_expired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelog',
            name='expired_date',
        ),
    ]
