# Generated by Django 4.1 on 2023-11-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0031_remove_filelog_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='expired_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
