# Generated by Django 4.1 on 2023-11-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0032_filelog_expired_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filelog',
            old_name='expired_date',
            new_name='expiry_date',
        ),
    ]
