# Generated by Django 4.1 on 2023-12-14 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0033_rename_expired_date_filelog_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_fullname', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=50)),
                ('agency', models.CharField(default='Default Agency Name', max_length=50)),
                ('upload_file', models.FileField(upload_to=files.models.get_upload_path)),
                ('renewal_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
