# Generated by Django 4.1 on 2024-01-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0034_person_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_document',
            name='company',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
