# Generated by Django 4.1 on 2024-01-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0037_person_document_agency_person_document_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_document',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='person_document',
            name='company',
        ),
    ]
