# Generated by Django 4.1 on 2024-01-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0038_remove_person_document_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_document',
            name='agency',
            field=models.CharField(default='Default Agency Name', max_length=50),
        ),
        migrations.AddField(
            model_name='person_document',
            name='company',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
